#!/usr/bin/env ruby
# frozen_string_literal: true

IMAGE = 'zrpaplicacoes/docker-in-rails'

require 'optparse'
require 'ostruct'

# Parse user params
options = {}

OptionParser.new do |opt|
  opt.on('-r', '--ruby RUBY_VERSION', 'Ruby Version') { |o| options[:ruby_version] = o }
  opt.on('-t', '--tag TAG', 'Tag') { |o| options[:tag] = o }
end.parse!

config = {}
config[:tag] ||= 'nightly'
config[:ruby_version] ||= '2.4.1'
config[:baseimage] ||= "ruby:#{config[:ruby_version]}-alpine"

# Build the image
puts "Building #{IMAGE}:#{config[:tag]} image..."

system('docker', 'build',
       '-f', "#{config[:baseimage]}.Dockerfile",
       '-t', "#{IMAGE}:#{config[:ruby_version]}-#{config[:tag]}", '.')
