#!/bin/bash

IP=$(hostname -i)

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

function aws_region_name {
  case $1 in
    us-east-1)
      echo -e "Virginia"
      ;;
    us-east-2)
      echo -e "Ohio"
      ;;
    us-west-1)
      echo -e "California"
      ;;
    us-west-2)
      echo -e "Oregon"
      ;;
    ap-northeast-1)
      echo -e "Tokyo"
      ;;
    ap-northeast-2)
      echo -e "Seoul"
      ;;
    ap-northeast-3)
      echo -e "Osaka-Local"
      ;;
    ap-south-1)
      echo -e "Mumbai"
      ;;
    ap-southeast-1)
      echo -e "Singapore"
      ;;
    ap-southeast-2)
      echo -e "Sydney"
      ;;
    ca-central-1)
      echo -e "Central"
      ;;
    cn-north-1)
      echo -e "Beijing"
      ;;
    cn-northwest-1)
      echo -e "Ningxia"
      ;;
    eu-central-1)
      echo -e "Frankfurt"
      ;;
    eu-west-1)
      echo -e "Ireland"
      ;;
    eu-west-2)
      echo -e "London"
      ;;
    eu-west-3)
      echo -e "Paris"
      ;;
    sa-east-1)
      echo -e "Sao Paulo"
      ;;
    *)
      echo -e ""
  esac
}

export PS1="\[$BPurple\]@\u\[$Color_Off\]\[$BCyan\]":$IP/32"\[$Color_Off\] \t \[$BGreen\]$(if [ -z $AWS_REGION ]; then echo -e ""; else echo -e "($(aws_region_name $AWS_REGION)) " ; fi)\[$Color_Off\]$(if [ "$RAILS_ENV" = "production" ]; then echo -e "⚠️  "; else echo -e ""; fi)\w $\[\033[00m\] ";
