#!/bin/ash

set -e

source /usr/local/bin/colors
source /usr/local/bin/logo

# Load Environment
echo ":::: Loading environment..."
eval "$(load_env)"
echo -e "${BGreen}:::: Environment loaded!${Color_Off}"

# Export default variables
export APP_PATH='/srv/app'
export APP_TEMP_PATH="$APP_PATH/tmp"
export APP_SETUP_LOCK="$APP_TEMP_PATH/setup.lock"
export APP_SETUP_WAIT="2"

# Functions
lock_setup() { mkdir -p $APP_TEMP_PATH && touch $APP_SETUP_LOCK; }
unlock_setup() { rm -rf $APP_SETUP_LOCK; }
wait_setup() { echo -e "${BRed}Waiting for app setup to finish...${Color_Off}"; sleep $APP_SETUP_WAIT; }
gems_up_to_date() { bundle check 1> /dev/null; }
configure_user() {
  set -e
  export UID=${USER_ID:-9001}
  export USER=${USER:-app}
  export HOME=/home/$USER
  
  if [ ! "$USER" = "root" ]; then
    echo ":::: Starting with (UID: $UID, USER: $USER, HOME: $HOME)"
    adduser -u $UID -s /bin/ash -h $HOME -D $USER || echo "User already exists..."
    addgroup $USER root
    
    # change all application files ownership to current user
    if [ -d "$APP_PATH" ]; then
      chown $USER:$USER $APP_PATH -R
    fi
  fi
}

# Install script dependencies
gem install colorize --no-rdoc --no-ri --no-user-install

if [ "$RAILS_ENV" = "development" -o "$RAILS_ENV" = "test" ]; then
  export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
  
  echo -e "${BGreen}:::: Booting application on development/test mode...${Color_Off}"
  echo ":::: RACK_ENV=$RACK_ENV and RAILS_ENV=$RAILS_ENV"
  echo ":::: Database is set as $DATABASE_URL"

  trap unlock_setup HUP INT QUIT TERM EXIT

  if [ -z "$1" ]; then set -- /bin/ash "$@"; fi

  if [ -d "$APP_PATH" -a "$1" = "rails" -o "$1" = "sidekiq" -o "$1" = "rake" -o "$1" = "bundle" -o "$1" = "shoryuken" ]; then
    while [ -f $APP_SETUP_LOCK ]; do wait_setup; done
    
    lock_setup
    
    echo ":::: Checking system bundle"
    if ! gems_up_to_date; then
      echo ":::: Installing/Updating Rails dependencies"
      bundle install
      echo -e "${BGreen}:::: Successfully updated dependencies${Color_Off}"
    else
      echo -e "${BGreen}:::: Dependencies are up to date${Color_Off}"
    fi
    
    echo ":::: Checking database consistency against current schema..."
    if [ "$RAILS_ENV" = "test" ]; then
      bundle exec rake db:drop
    fi
    if [ -z $DATABASE_ADAPTER ]; then
      bundle exec setup_pg
    elif [ "$DATABASE_ADAPTER" = "mysql2" ]; then
      bundle exec setup_mysql2
    fi
    
    unlock_setup
    
    rm -rf "${APP_TEMP_PATH}/pids/server.pid" 2>/dev/null
  fi
fi

if [ "$RAILS_ENV" = "production" ]; then
  echo -e "${BRed}:::: Booting application on production mode...${Color_Off}"
fi

if [ -z $RAILS_ENV ]
then
  echo -e "${BRed}:::: Booting application on unknow mode...${Color_Off}"
fi

# calls command
configure_user
echo -e ":::: Executing the given command: ${BBlue}'$@'${Color_Off}"
exec /usr/local/bin/gosu $USER "$@"
