#!/usr/local/bin/ruby
# frozen_string_literal: true

def parse(file_contents)
  file_contents.each_line.inject('') do |result, line|
    return result unless (line =~ /(RAILS_ENV|RACK_ENV)/).nil?
    result + "export #{line.chomp};"
  end
end

if File.exist?('.env') || File.exist?('.env.sample')
  if ENV['RAILS_ENV'] != 'production'
    filename = File.exist?('.env') ? '.env' : '.env.sample'
    puts parse(File.read(filename))
  end
end
