#!/usr/local/bin/ruby
# frozen_string_literal: true

require 'optparse'
require 'colorize'

raise "not implemented"

unless ENV['DATABASE_URL']
  puts "Database not configured!".colorize(:red)
  exit(1)
end
 
config = {}

OptionParser.new do |opt|
  opt.on('-d', '--dump', 'Dump file name') { |o| config[:dump] = o }
end.parse!

config[:dump] ||= Dir.glob("*").max_by {|f| File.mtime(f)}

puts "Restoring database #{ENV['DATABASE_URL']} with dump #{config[:dump]}"


