#!/usr/bin/env ruby
# frozen_string_literal: true

require 'colorize'

puts "[INFO] Running application quality approvement...".colorize(:green)

if ENV['RAILS_ENV'] && ENV['RAILS_ENV'] == 'test'
  echo "Testing application security..."
  exec('brakeman', '-z', '-A', '-q')
  puts "Testing spec/ folder...".colorize(:green)
  
  exec('check_or_setup_db')
  exec('rspec', 'spec')
  
  puts "Finished quality approvement...".colorize(:green)
  0
else
  echo "Environment error... RAILS_ENV should be test, currently is #{ENV['RAILS_ENV'] || 'empty'}"
  1
end
