#!/usr/local/bin/ruby
# frozen_string_literal: true

require 'bundler'
Bundler.setup

puts "\033[0;32m:::: Running application quality approvement...\033[0m"

if ENV['RAILS_ENV'] && ENV['RAILS_ENV'] == 'test'
  export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
  puts "Testing application security..."
  system('bundle', 'exec', 'brakeman', '-z', '-A', '-q')

  puts "\033[0;32mTesting spec/ folder...\033[0m"
  if ENV['DATABASE_ADAPTER'] == 'postgresql'
    system('bundle', 'exec', 'setup_pg')
  elsif ENV['DATABASE_ADAPTER'] == 'mysql2'
    system('bundle', 'exec', 'setup_mysql2')
  else
    system('bundle', 'exec', 'setup_pg')
  end
  sleep 5
  result = system('bundle', 'exec', 'rspec', 'spec')

  puts "\033[0;32mFinished quality approvement...\033[0m"
  result ? 0 : 1
else
  puts ":::: Environment error... RAILS_ENV should be test, currently is #{ENV['RAILS_ENV'] || 'empty'}"
  1
end
